version: '3.8'

services:
  mysql:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ultimatum
      MYSQL_DATABASE: ultimatum
    volumes:
      - mysql-data:/var/lib/mysql

  spring-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - mysql

volumes:
  mysql-data:

networks:
  default:
    name: ultimatum-network
    driver: bridge
