version: '3.8'

services:
  mysql:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ultimatum
      MYSQL_DATABASE: maison_chap
      MYSQL_USER: ultimatum
      MYSQL_PASSWORD: ultimatum
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/maison_chap

    volumes:
      - mysql-data:/var/lib/mysql

  spring-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - mysql

volumes:
  mysql-data:

networks:
  default:
    name: ultimatum-network
    driver: bridge
