spring:
  mvc:
    static-path-pattern: /**
  datasource:
    username: root
    password:
    url: jdbc:mysql://localhost:3306/maison_chap
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
        poolName: Hikari
        auto-commit: false
        data-source-properties:
          cachePrepStmts: true
          prepStmtCacheSize: 250
          prepStmtCacheSqlLimit: 2048
          useServerPrepStmts: true
  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
          dialect: org.hibernate.dialect.MySQL8Dialect
  application:
    name: maison-chap
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  mail:
    host: smtp.titan.email
    port: 587
    username: maisonchap@ultimatumworkspace.works
    password: Ultima@1
    protocol: smtp
    properties:
      mail:
        smtp:
          connection-timeout: 8000
          timeout: 8000
          write-timeout: 8000
          auth: true
          starttls:
            enable: true
  messages:
    basename: i18n/messages

  thymeleaf:
    cache: true
    mode: HTML
    encoding: UTF-8
    servlet:
      content-type: text/html
  banner:
    location: banner.txt
server:
    port: 8080

application:
  frontend:
    url: http://192.168.143.216:4200
    login:
      endpoint: /login
    renew-account:
      endpoint: /renew-validation
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days
file:
  upload-dir: src/main/resources/static/uploads

mail:
    from: maisonchap@ultimatumworkspace.works
    baseUrl: http://192.168.143.216:8080
