name: Docker CI/CD GitHub Action

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Build with Maven
      run: mvn -B package --file pom.xml -DskipTests

    - name: Start services
      run: |
        docker-compose up -d
        docker-compose ps
        docker-compose logs -f &
        mvn clean test -Dspring.datasource.url=jdbc:mysql://localhost:3306/ultimatum

    - name: Stop services
      run: docker-compose down
