name: Test job for CI  java spring boot app
on:
    push:
        branches:
        - main
    pull_request:
      branches:
        - main

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v2
        - name: Set up JDK 11
          uses: actions/setup-java@v2
          with:
            java-version: '17'
            distribution: 'temurin'

        - name: Build with Maven
          run: mvn -B package --file pom.xml
        - name: Test with Maven
          run: mvn test --file pom.xml

        - name: implement test unit
          run: mvn test --file pom.xml



