name: Docker ci/cd github action

on: #ce qui déclenche le workflow
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs: #ce que le workflow fait 
  build:

    runs-on: ubuntu-latest #on indique que l'on va utiliser une machine ubuntu
    steps:

    - name: Checkout #on récupère le code source de notre projet
      uses: actions/checkout@v2

    - name: Set up JDK 17 #on installe java 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Build with Maven #on build le projet avec maven
      run: mvn -B package --file pom.xml -DskipTests

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: ultimatum
          MYSQL_DATABASE: ultimatum
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3


    - name: Start services
      run: |
        docker-compose up -d
        docker-compose ps
        docker-compose logs -f &
        mvn clean test -Dspring.datasource.url=jdbc:mysql://localhost:3306/maison_chap

    - name: Stop services
      run: docker-compose down
